configured_endpoints: 53
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/delegate%2Fdelegate-ceaec29bbf0e83ba54fdc31d9b2c4183907f9522233adbb85673b09c849b75de.yml
openapi_spec_hash: 54d7ad0ec2a2ce57ffd7bd6df2ec5945
config_hash: 21a27fa2df7fcc6ecd34564dbbd2f93d
